"""baseline schema

Revision ID: f838d5f10e83
Revises: 
Create Date: 2026-04-21 14:25:25.157358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f838d5f10e83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('agency_id', sa.String(length=50), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('long_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.Column('text_color', sa.String(length=6), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stops',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('location_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('route_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('direction_id', sa.String(length=10), nullable=False),
    sa.Column('direction_name', sa.String(length=255), nullable=True),
    sa.Column('encoded_polyline', sa.Text(), nullable=True),
    sa.Column('stop_ids_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'direction_id', name='uq_route_direction')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('stop_id', sa.String(length=50), nullable=False),
    sa.Column('direction_id', sa.String(length=10), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_id', 'direction_id', name='uq_route_stop_dir')
    )
    op.create_table('user_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('direction_id', sa.String(length=10), nullable=False),
    sa.Column('from_stop_id', sa.String(length=50), nullable=False),
    sa.Column('to_stop_id', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['to_stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'route_id', 'direction_id', 'from_stop_id', 'to_stop_id', name='uq_user_segment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_segments')
    op.drop_table('route_stops')
    op.drop_table('route_directions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))

    op.drop_table('users')
    op.drop_table('stops')
    op.drop_table('routes')
    # ### end Alembic commands ###
